---
title: "My Portfolio"
---

This website contains my portfolio for my [Data Science for Psychologists](https://datascience4psych.github.io/DataScience4Psych/) class.
The portfolio consists of 11 projects which have further my understanding of R or data science in some way. The projects tend to fall into one of two categories: Deep-dives into a topic I feel like I should know more about to improve my coding or solutions to real-world problems that requires me to use R to solve novel problems and offer practice with programming. I have aimed to make a fairly even distribution between these two types of projects, so that I will both learn more advanced R topics and advance my code knowledge, as well as get practice using these skills in realistic problems, that are often not as straight-forward as in the practice questions and labs we are using in this course.

The focus on the deep-dives has been to learn about the topic and then write it up in a way so that I can come back and use it for reference later. The topics of these deep-dives are often broad and I will continue to learn as I get more experience with programming. The deep dives are therefore dynamic documents that will continue to evolve beyond this course, as I run into new features, tricks, and problems. They are therefore far from being "finished", but instead a beginning on my journey to learn about the topic. I aspire to one day write them up as tutorials that can be useful for others, but until I get that far, they will serve as references when coding and a place to collect everything I learn about the topic. When I start getting through the most important features to learn about, I might shift to trying to write it up clearer and with more explanation and examples.

The applied problems have on the other hand been more focused on solving a real-world problem and whatever that has required is what I have gotten practice in. These projects have often been really challenging, but also really interesting, as they have required using functions in new combinations or learning new functions. This is also where I feel like I have solidified my R skills. They have also at times been a good test of patience, as it has often taking many tries to find some code or algorithm that works with the specific scenario I have had.

All in all, I have learned a lot working on this portfolio and I hope that you might too looking over it!

<!-- The "br" part adds another empty line so that I get an additional line before signing the introduction -->

 <br>

Sincerely,

Linn Zapffe