---
title: "Improving the Code for the Grading Contract"
editor_options: 
  markdown: 
    wrap: 72
---

I found a few areas of improvement in the code for the
grading contract. After testing out a few things, it looks like the
original code is ok, but could be scaled up to add in some additional
useful features. The following project will try to do this.

Goals for the project:

* Get familiar with some of the functionalities I don't know as well
    with Rmarkdown, such as place holders
* Get practice reading and understandig others' code and editing it
* Practice designing/updating code to solve a problem identified in
    the code, in other words, translating an idea to code.
* Working with dates in R (tidyverse)
* Add some features that I would like for the contract to have and therefore have it bug me less


## Rmarkdown Basics

The following are some notes from things I have learned or wanted to remember while working on this project:

- To make a new paragraph, make two new lines, not just one
- When making bullet point lists, you can use "*" or "-", but there has to be a new line before the start of the first bullet point for the formatting to work correctly
- To embed a link with text, write the text you want displayed in brackets and right after put the link in parenthesis
- You can also make a new paragraph by ending the last line of a paragraph with two spaces. Or add a backslash at the end of the line.
- ">" before some text leads to a block quote
- "[ ]" creates an unchecked box, while [x] creates a checked box. In html, the formatting gets weird with checked boxes. It turns bold automatically and adds extra space for the next line. However, if making it a Github document, it shows up with the expected formatting
- Write < ! - - - text - - > (with no spaces between the characters) to write a comment in the Rmarkdown document that does not show up on the rendered output. 
  - Note that if you write the code for in-text r code (tick mark, r, code, and tick mark) in this type of comment, it will actually run that code
- You get **bold** text from adding "**" before and after the text you want in bold


Useful links:

- [Rmarkdown instructions with examples and code](http://www.ece.ualberta.ca/~terheide/rmarkdown-how-to/markdown.html)


## The Current Contract Code

The following is the content of the current  Rmarkdown document for the contract. It is pasted here for reference so that one can see what the original contract looked liked. In addition, this copy will be used to take notes while going over it to understand and document how the original code works. There will therefore be many comments added throughout this code to explain what the current code is doing. This will help me better understand what to change and how. Throughout working with the original document, I have tinkered with it to figure out what the different parts of the code do. That process is not documented here, as that would be too time consuming. So, here is the original contract with my comments added as block quotes. All of the formatting that makes code runnable has been removed so that we will see the code and not the output of it, as well as so that it doesn't take up additional time executing the code when knitting the document.


> The following is the YAML header.

>It states the title of the document, the date, which is today's date retrieved from the computer/system running the document.

title: Grading Contract  
date: "format(Sys.time(), '%B %d %Y')"  

> The output is currently set to html, even though the original was a github document (.md), as it is quicker to visualize html documents when working with Rmarkdown. 

output: html_document  

> Then we have the parameters that will be used during the rest of the contract. This is what makes the document dynamic. The information required is the first date for the class (weekonemonday), the thesis deadline, and the date for spring break. Then it asks for the name of the person writing the contract, how many labs and projects they are doing, the grade they want, and the day of the week they want the due dates to be on. The grade and due date day has explicit options that the user can chose between several grades and several days, from what is included under "choices". Then whatever the individual wants is what is put under "value".

params:  
  weekonemonday: "2025-01-13"  
  thesisdeadline: "2025-03-21"  
  springbreak: "2025-03-10"  
  name: Linn Zapffe  
  labs: 11  
  portfolios: 10  
  grade:  
    label: Grade  
    value: A  
    input: select  
    choices:  
    - A  
    - B  
    - Pass  
  startweek:  
    label: Weekly Due Date  
    value: Monday  
    input: select  
    choices:  
    - Monday  
    - Tuesday  
    - Wednesday  
    - Thursday  
    - Friday


> This is a code block loading the library tidyverse. tidyverse is used to handle date objects better.

{r setup, include=FALSE}

library(tidyverse)

# R Syllabus Scheduler

> Here we define a function that is giving formatted output with the right values (e.g. dates) based on the parameters we have given in the YAML header. This function will be used to fill in most of the place holders in the contract.

advdate <- function(weekonemonday,
                    week,
                    topic =  NULL,
                    assignment = NULL,
                    unit = "Module ") {  

> The function takes 5 parameters. One is what we defined as the date for the first Monday of classes. The second one is which week we are in, indexed by an integer. Then what topic we are on (which is indexed from a list we will define later, called topic). The next one is the assignment, which seems to be the same as the due date day, for example Monday. If this is null, it gives you a string with the module number, start and end date of the week, and the topic for that module. However, if it is set to be a day (not null), it will instead give a simplified string with just the date of the day that the deadline is on that week. Lastly, unit seems to just store the string "module" that is pasted into the strings. These last three parameteres have default values, so they are optional.

> The below code takes what week we are in and calculates the date for each weekday, starting from when the first day of class is. The date variable weekonemondy is converted to a date object later in the code (but before the function is called) and stored in the variable dayone. If not, the code wouldn't run due to trying to run operations that require an object to be date when it isn't. To illustrate the output of this code, tmon for week 1 could be "01/13".

  # as.Date does not like piping
  
  tmon <- as.Date(weekonemonday + 7 * (week - 1)) %>% 
    format(format = "%m/%d")  
    
  ttue <- as.Date(weekonemonday + 1 + 7 * (week - 1)) %>%
    format(format = "%m/%d")  
  twed <- as.Date(weekonemonday + 2 + 7 * (week - 1)) %>%
    format(format = "%m/%d")  
  tthu <- as.Date(weekonemonday + 3 + 7 * (week - 1)) %>%
    format(format = "%m/%d")  
  tfri <- as.Date(weekonemonday + 4 + 7 * (week - 1)) %>%
    format(format = "%m/%d")  
  tsat <- as.Date(weekonemonday + 5 + 7 * (week - 1)) %>%
    format(format = "%m/%d")  
  tsun <- as.Date(weekonemonday + 6 + 7 * (week - 1)) %>%
    format(format = "%m/%d")  
    
> zadv formats the week to have two numbers, so that e.g. week 1 is formatted as 01

  zadv <- sprintf("%02d", week)  
  
  
> The following code has several if statements, leading to different formatting of a string with information about the module number, start and end dates, and topic to be covered.

> The first condition is if there is no topic or assignment (which is set to NULL by default). This will therefore mostly occur if there are no more topics to go over. It will produce something like "Module 01, 01/13 - 01/17". We don't seem to use this in  the code, it is probably just there to catch a situation in which there are fewer modules than weeks in the semester.

  if (is.null(topic) & is.null(assignment)) {  
    tmp <- paste0(unit, zadv, ", ", tmon, " - ", tfri)  
    
> If assignment (the day of the week assignments are due on) is still empty, but there is a topic, you get formatting similar to "01/17". Paste0 is used to paste the results together. However, I don't think you need paste0() here when there is only one variable. You also probably don't need to catch all varioations of the spelling of the weekdays, as the options of how to write it that work with the code, are in the choices for that parameter in the YAML header.
    
  } else if (!is.null(assignment)) {  
    if (assignment %in%  
        c("Friday",  
          "friday",  
          "f",  
          "fri",  
          "FRI")) {  
      tmp <- paste0(tfri)  
    } else if (assignment %in%  
               c("thursday",  
                 "Thursday",  
                 "thurs",  
                 "r",  
                 "R")) {  
      tmp <- paste0(tthu)  
    } else if (assignment %in%  
               c("wednesday",  
                 "Wednesday",  
                 "w",  
                 "wed",  
                 "W")) {  
      tmp <- paste0(twed)  
    } else if (assignment %in%  
               c("Tuesday",  
                 "tues",  
                 "t",  
                 "Tue")) {  
      tmp <- paste0(ttue)  
    } else if (assignment %in%  
               c("monday",  
                 "Monday",  
                 "m",  
                 "mon")) {  
      tmp <- paste0(tmon)  
    }  
    
> If there is both a topic and assignment (due date of the week), then you get something like the following string: "Module 01, 01/13 - 01/17 : What is Data Science and Meet the Toolkit"
    
  } else{  
    tmp <- paste0(unit, zadv, ", ", tmon, " - ", tfri, " : ",   topic[week])  
  }  
  
> Lastly, tmp, the formatted string, is returned from the function, so that we can access it outside of the function.

  return(tmp)  
}  

> I don't know what the following code was meant to do.

#if(TRUE){  
#    
#  dayone <- as.Date("2022-01-10")  
#  startweek <- "Friday"  
#} else {  
  
> This code assigns the parameters given above to new variable names. This part is not necessary, but makes the contract part a little more readable. Also, it formats the weekonemonday to be a date object instead of a string. Note that this happens outside of the function, but before it is called.
  
dayone <- as.Date(params$weekonemonday)  
startweek <- params$startweek  


  
#}


> Making a list with all the topics in the R course, which is used to get the topic names with indexing when making the schedule in the contract. (They therefore have to be in the right order).

topic = c(  
  "What is Data Science and Meet the Toolkit",  
  "Data and Visualization",  
  "Grammar of data wrangling",  
  "Data types and Data Transformations",  
  "Tips for effective data visualization",  
  "Scientific studies and confounding",  
  #  "Spring Break",#  "",  
  "Web scraping",  
  "Functions",  
  "Data and Ethics",  
  "Fitting and interpreting models",  
  "Prediction and overfitting",  
  "Cross validation",  
  "Quantifying uncertainty",  
  "Interactive web apps",  
  "Special Topics"  
)  



<!-- This contract is adapted from Annie Somerville's contract https://github.com/anniehsom -->


> The following is the contract with the parameters entered throughout the text, to make the document dynamic and easily adjustable for each individual. The code does also call upon the advdate function defined earlier.

### Contract Grades – “params$grade” Contract

I, params$name, agree to :

1) Earn “Satisfactory” on params$labs self-paced lab assignments on the schedule specified below. Getting a grade of "Satisfactory" requires that: 
* I have attempted all steps of the assignment. If unable to complete steps due to unresolved questions, I have asked questions in Github FAQs or during the help sessions, or I have Googled the issue and shown effort to resolve questions;
	* I have checked that files, repos, or projects appear on my Github account and are accessible;
	* I feel like I have spent an adequate amount of time and energy on assignments; 
2) Produce at least params$portfolios “Satisfactory” portfolio pieces on the schedule specified below. Getting a grade of "Satisfactory" requires that: 
    * I have designed a portfolio project that I think challenges my understanding of programming, explores a topic I want to know more about, or targets something I feel like I need more practice with;
   * I have checked that files, repos, or projects appear on my Github account and are accessible;
    * I feel like I have spent an adequate amount of time and energy on the projects; 



### SCHEDULE

> The following formatting with no spaces and all bold for the checklists doesn't look that good when knitted in html. The contract is made to be outputted in a github document, which makes the formatting more like what would be expected given the code.

- [ ] advdate(dayone, 1, topic)
  - [ ] Finish Lab 1 by startweek:  advdate(dayone, 2, assignment=startweek)
- [ ] advdate(dayone, 2, topic)
  - [ ] Finish Lab 2 by startweek:  advdate(dayone, 3, assignment=startweek)
  - [ ] Propose your contract to Mason by startweek:  advdate(dayone, 3, assignment=startweek)
- [ ]  advdate(dayone, 3, topic)
  - [ ] Finish Lab 3  by startweek:  advdate(dayone, 4, assignment=startweek)
  - [ ] Finish portfolio piece 1 by startweek:  advdate(dayone, 4, assignment=startweek)
- [ ] advdate(dayone, 4, topic)
  - [ ] Finish Lab 4  by startweek:  advdate(dayone, 5, assignment=startweek)
- [ ] advdate(dayone, 5, topic)
  - [ ] Finish Lab 5  by startweek:  advdate(dayone, 6, assignment=startweek)
  - [ ] Finish portfolio piece 2 by startweek:  advdate(dayone, 6, assignment=startweek)
- [ ] advdate(dayone, 6, topic)
  - [ ] Finish Lab 6 by startweek:  advdate(dayone, 7, assignment=startweek)
  - [ ] Schedule a check-in with Mason by startweek:  advdate(dayone, 7, assignment=startweek)
- [ ] advdate(dayone, 7, topic)
  - [ ] Finish Lab 7 by startweek:  advdate(dayone, 8, assignment=startweek)
  - [ ] Finish portfolio piece 3 by startweek:  advdate(dayone, 8, assignment=startweek)
- [ ] advdate(dayone, 8, topic)
  - [ ] Finish Lab 8 by startweek:  advdate(dayone, 9, assignment=startweek)
- [ ] advdate(dayone, 0, topic)
  - [ ] Finish Lab 9 by startweek:  advdate(dayone, 10, assignment=startweek)
  - [ ] Finish portfolio piece 4 by startweek:  advdate(dayone, 10, assignment=startweek)
- [ ] advdate(dayone, 10, topic)
  - [ ] Finish Lab 10 by startweek:  advdate(dayone, 11, assignment=startweek)
- [ ] advdate(dayone, 11, topic)
  - [ ]  if(params$labs>=11) paste0(" Finish Lab 11 by ",startweek,": ",advdate(dayone, 12, assignment=startweek))
  - [ ] Finish portfolio piece 5 by startweek:  advdate(dayone, 12, assignment=startweek)
- [ ] advdate(dayone, 12, topic)
  if(params$labs>=12) paste0(" - Finish Lab 12 by ",startweek,": ",advdate(dayone, 12, assignment=startweek))
  - [ ] Finish portfolio piece 6 by startweek:  advdate(dayone, 13, assignment=startweek)
- [ ] advdate(dayone, 13, topic)
  if(params$labs>=13) paste0(" - Finish Lab 13 by ",startweek,": ",advdate(dayone, 14, assignment=startweek))
  - [ ] Finish portfolio pieces 7 and 8 by startweek:  advdate(dayone, 14, assignment=startweek)
- [ ] advdate(dayone, 14, topic)
  - [ ] Finish portfolio piece 9 by startweek:  advdate(dayone, 15, assignment=startweek)
- [ ] advdate(dayone, 15, topic)
  - [ ] Finish portfolio piece 10 by startweek:  advdate(dayone, 16, assignment=startweek)
- [ ] Portfolio completion
  - [ ] Due on startweek: advdate(dayone, 16, assignment=startweek)
  
  
### Further guidelines

- According to reasons discussed and agreed upon in advance with the     professor, there are some situations which might require some of these deadlines to be moved. If this is the case, I will reach out to the professor and agree on another deadline. The number of assignments that have to be completed satisfactory will not change.
- If the professor has any concerns about the assignments and whether     they reach the standards of being completed "satisfactory", the     professor will communicate these concerns with me and, if deemed     appropriate, offer an opportunity to correct them.
- I pertain the right to, at any time, switch out any of the modules and labs with another module or lab in the course or change the order of them from what is currently specified in the contract. This will not affect the number of labs or modules that are to be completed according to the contract. Any such changes will be noted in this contract for reference, but will not require notifying the professor.
- Any other part of this contract can be changed before the final grade is set if agreed upon by both myself and the professor.


# Goals For the New Contract

Things to improve:

* The code is generally poorly commented and some of it is not ordered chronologically considering the order in which humans tend to read code. mild spaghetti code (no offense). So, the new code will have much more extensive coding and will try to put things in the order it is read in by humans, to make the readability better.
* The variable names could sometimes be more enlightening, so these will be updated
* There are some parts of the function that are never used. This can be deleted and potentially dealt with as error checking instead, if needed. There are also some additional fail-safe's, like allowing for "Monday", "monday", "Mon", and "m", which doesn't seem necessary as the YAML header specifically states the available options to put in. If anyone puts in a shorthand that doesn't work with the code, they should be able to figure that out based on the options provided in the YAML header.
* The current code will only allow for the insertion of spring break if you add it as a topic. However, that will shift all the module numbers so that they do not align with the topic. This will be changed, so that they module number is correct for each topic.
* You can currently not have the weekly deadlines be on Sundays, which is a typical day to have deadlines on. I'll add the opportunity for the deadlines to be on Saturday and Sunday.
* It can be hard to understand the logic of the document, especially if one is not familiar with Rmarkdown yet. This is likely the case for several students, so I'll also write and include instructions on how to navigate the document and what it does throughout the contract.
* Now, one has to look to the syllabus to see how many labs and portfolio projects to finish given the desired grade. I will put this in automatically based on the grade they add that they want to contract for in their YAML header, so that the student don't need to provide it themselves.


# The Improved Contract

This is a copy of the improved contract, attached for reference. There might be minor variations between this version and the final version attached ("p01_contract.Rmd")in the ds_portfolio repository. However, The code should be more or less the same between the two versions.

Comments in the code have been changed out with block quotes, as the hash tag symbol would have been rendered as a header if not inside a code block. However, the comments that are here in the block quotes are the same as are in the improved template. In addition, there are comments that are only visible in the Rmarkdown document, but not in the knitted output (github file). These comments are to guide the students through how to use the contract. I will denote those here as "comment:", so that they are visible also in the output. 


title: Grading Contract  
date: "format(Sys.time(), '%B %d %Y')"  
output: github_document  
params:  
  mondayweekone: "2025-01-13"  
  thesisdeadline: "2025-03-21"  
  springbreak: "2025-03-10"  
  name: Linn Zapffe  
  grade:  
    label: Grade to write the contract for  
    value: A  
    input: select  
    choices:  
    - A  
    - B  
    - Pass  
  deadline_day:  
    label: Day of the weekly due dates  
    value: Sunday  
    input: select  
    choices:  
    - Monday  
    - Tuesday  
    - Wednesday  
    - Thursday  
    - Friday  
    - Saturday  
    - Sunday  
editor_options:  
  markdown:  
    wrap: 72  


Cooment: How to use this Rmarkdown document
The text above this comment is the YAML header. Change the variables under "params" into what is relevant for you and your situation. In cases where there are choices, you have to choose one of those choices. Make sure you spell your parameter the same was as one of the choices and also have the same capital or small letters.

The parameters that you have specified in the YAML header will be used in the rest of the code to change out place holders.

The gray boxes are r code. Since there is a "include = FALSE" command in the header of each code block, the code itself will be ran and used to produce the rest of the document. However, the code itself will not show up when you render/knit the document.

The first code chunk sets the number of labs and portfolio projects you need, based on what grade you are writing the contract for. You should double check that this number is the same as what is currently stated in the syllabus as being the requirement for that grade. The second code chunk defines some variables we need and the list with the topics for the modules. Double-check that all the modules that are currently available are in that list. If not, feel free to change that. The third code chunk defines a function that takes in some parameters (information you give it) and turns that into a string we use in the contract, for example with the relevant module names and dates.
-->

r setting number of assignments, include = FALSE

> Setting the required number of labs and portfolio projects given the grade the student wants to make the contract for


if (params$grade == "A") {
  n_labs <- 11
  n_portfolios <- 10
} else if (params$grade == "B") {
  n_labs <- 8
  n_portfolios <- 6
} else if (params$grade == "Pass") {
  n_labs <- 8
  n_portfolios <- 4
} 


r defining variables, include = FALSE

> Loading tidyverse, to deal with dates better

library(tidyverse)

> Defining the parameters as variables which makes it a little less cluttered during the contract itself

monday_week_one <- as.Date(params$mondayweekone)
deadline_day <- params$deadline_day
spring_break <- as.Date(params$springbreak)

> Defining a list with all the modules in it, which can be chosen from when making the schedule

modules_list = c(
  "Data Science",
  "Data and Visualization",
  "Tidyverse",
  "Data Diving with Tidyverse",
  "Effective Data Visualization",
  "Web scraping",
  "Functions and Automation",
  "Data and Ethics",
  "Modeling the Tidy way!",
  "Overfitting and Cross-validation",
  "Quantifying Uncertainty",
  "Base R and Simulating Data",
  "Large Language Models",
  "Interactive Web Apps",
  "Reproducible Reports",
  "Machine, Learn")


r dates and strings, include = FALSE

> Defining a function we can call when we need a string in the contract with the modules, dates, and/or date for the deadlines

  > The function takes four parameters. The first is the date of the first Monday of classes, the second is the week number, the third is the module for that week, and the last one is the deadline day chosen earlier
  
string_details <- function(monday_week_one,
                    week_num,
                    module_num = NULL,
                    modules_list =  NULL,
                    deadline_day = NULL) {

           
  > Calculating the date for the weekday, based on the inputted week
  
  > We keep the variable, date_monday, in date form for Monday, as we will use it to check whether it is the week of spring break later in the code. The as.Date() allows for the calculations to occur with the dates, which would not be possible if they were treated as string. The code won't run if it doesn't have the as.Date() function there.
  
  date_monday <- as.Date(monday_week_one + 7 * (week_num - 1))
  
  > Then we format the date into a string (happens automatically with format()) in the form of two numbers for day and month, e.g. "03/03"
  
    > For the rest of the days, we just keep this string version
    
  date_monday_str <- format(date_monday, format = "%m/%d")  
  date_tuesday_str <- as.Date(monday_week_one + 1 + 7 * (week_num - 1)) %>%
    format(format = "%m/%d")  
  date_wednesday_str_str <- as.Date(monday_week_one + 2 + 7 * (week_num - 1)) %>%
    format(format = "%m/%d")  
  date_thursday_str <- as.Date(monday_week_one + 3 + 7 * (week_num - 1)) %>%
    format(format = "%m/%d")  
  date_friday_str <- as.Date(monday_week_one + 4 + 7 * (week_num - 1)) %>%
    format(format = "%m/%d")  
  date_saturday_str <- as.Date(monday_week_one + 5 + 7 * (week_num - 1)) %>%
    format(format = "%m/%d")  
  date_sunday_str <- as.Date(monday_week_one + 6 + 7 * (week_num - 1)) %>%
    format(format = "%m/%d")  
  
  > Format the week number with two numbers, e.g. "02"
  
  module_string <- sprintf("%02d", module_num)
  
  > Creating the string, based on what type of information is given. This determines what format the string should have
  
  > First if checks for whether it is spring break. If it is, then there is no module to do
  
  if (date_monday == spring_break) {  
  
  > paste0 adds the parts in it together to a string, separated by space
    
    str_line <- paste0("Spring break! - ", date_monday_str, " - ", date_sunday_str)  
  } else if (!is.null(deadline_day)) {  
    if (deadline_day == "Monday") {  
      str_line <- date_monday_str  
    } else if (deadline_day == "Tuesday") {  
      str_line <- date_tuesday_str  
    } else if (deadline_day == "Wednesday") {  
      str_line <- date_wednesday_str  
    } else if (deadline_day == "Thursday") {  
      str_line <- date_thursday_str  
    } else if (deadline_day == "Friday") {  
      str_line <- date_friday_str  
    } else if (deadline_day == "Saturday") {  
      str_line <- date_saturday_str  
    } else if (deadline_day == "Sunday") {  
      str_line <- date_sunday_str  
    }  
    
  > Creating a string with the module, module number, dates for the week, and the topic for the module
    
  } else{
    str_line <- paste0("Module ", module_num, ", ", date_monday_str, " - ", date_sunday_str, " : ", modules_list[module_num])
  }
  
  > Return the string so that it can be accessed outside of the function
  
  return(str_line)
}



Comment: The next part here is the text that will actually be displayed in the document. The #, ##, or ### before some text indicates that this is a header. The number of "#"'s correspond to the level of the heading. So, # Heading will be in a bigger font than ## Header.

The text that consists of "tick"r text"tick" (I can't actually write it with the ticks here, as that would have been interpreted by r as code to run) is in-line r code. It will run the r code and the output will be pasted there in the text when you render/knit the document. Any call to params$[input parameter here] calls the parameter you inputted in the YAML header. So, for example, if you put in A as a grade, the string below will produce a text stating "Terms to Get a Grade of "A"".
The r codes with the parameters should paste the value or text that you need. If it seems wrong, double-check that you put in the right parameter (e.g. didn't misspell something). 

There is also some code that calls a function called string_details. This is the function we defined (made) earlier to make the strings we need. The parameters (values) we put in the parameter when calling the function determines what we get from it.

Read over the text for the contract and change or add anything you want to change.
-->


## Terms to Get a Grade of “params$grade”

I, params$name, agree to :

1)  Earn “Satisfactory” on r n_labs self-paced lab assignments on the
    schedule specified below. Getting a grade of "Satisfactory" requires
    that:
    - I have attempted all steps of the assignment. If unable to complete steps due to unresolved questions, I have asked questions in Github FAQs or during the help sessions, or I have Googled the issue and shown effort to resolve questions;
    - I have checked that files, repos, or projects appear on my Github account and are accessible;
    - I feel like I have spent an adequate amount of time and energy on the assignment;

2)  Produce at least r n_portfolios “Satisfactory” portfolio pieces on
    the schedule specified below. Getting a grade of "Satisfactory"
    requires that:
    - I have designed a portfolio project that I think challenges my understanding of programming or data science, explores a topic I want to know more about, or targets something I feel like I need more practice with;
    - I have checked that files, repos, or projects appear on my Github account and are accessible;
    - I feel like I have spent an adequate amount of time and energy on the projects;
        

### Schedule

- [ ] **string_details(monday_week_one, 1, 1, modules_list)**
    - [ ] Finish Lab 1 by deadline_day:
        string_details(monday_week_one, 1, deadline_day=deadline_day)
- [ ] **string_details(monday_week_one, 2, 2, modules_list)**
    - [ ] Finish Lab 2 by deadline_day:
        string_details(monday_week_one, 2, deadline_day=deadline_day)
    - [ ] Propose your contract to Mason by deadline_day:
        string_details(monday_week_one, 2, deadline_day=deadline_day)
- [ ] **string_details(monday_week_one, 3, 3, modules_list)**
    - [ ] Finish Lab 3 by deadline_day:
        string_details(monday_week_one, 3, deadline_day=deadline_day)
    - [ ] Finish portfolio piece 1 by deadline_day:
        string_details(monday_week_one, 3, deadline_day=deadline_day)
- [ ] **string_details(monday_week_one, 4, 4, modules_list)**
    - [ ] Finish Lab 4 by deadline_day:
        string_details(monday_week_one, 4, deadline_day=deadline_day)
- [ ] **string_details(monday_week_one, 5, 5, modules_list)**
    - [ ] Finish Lab 5 by deadline_day:
        string_details(monday_week_one, 5, deadline_day=deadline_day)
    - [ ] Finish portfolio piece 2 by deadline_day:
        string_details(monday_week_one, 5, deadline_day=deadline_day)
- [ ] **string_details(monday_week_one, 6, 6, modules_list)**
    - [ ] Finish Lab 6 by deadline_day:
        string_details(monday_week_one, 6, deadline_day=deadline_day)
    - [ ] Schedule a check-in with Mason by deadline_day:
        string_details(monday_week_one, 6, deadline_day=deadline_day)
- [ ]  **string_details(monday_week_one, 7, 7, modules_list)**
    - [ ] Finish Lab 7 by deadline_day:
        string_details(monday_week_one, 7, deadline_day=deadline_day)
    - [ ] Finish portfolio piece 3 by deadline_day:
        string_details(monday_week_one, 7, deadline_day=deadline_day)
- [ ] **string_details(monday_week_one, 8, 8, modules_list)**
    - [ ] Finish Lab 8 by deadline_day:
        string_details(monday_week_one, 8, deadline_day=deadline_day)
- [ ] **string_details(monday_week_one, 9, 9, modules_list)**
- [ ] **string_details(monday_week_one, 10, 9, modules_list)**
    - [ ] Finish Lab 9 by deadline_day:
        string_details(monday_week_one, 10, deadline_day=deadline_day)
    - [ ] Finish portfolio piece 4 by deadline_day:
        string_details(monday_week_one, 10, deadline_day=deadline_day)
- [ ] **string_details(monday_week_one, 11, 10, modules_list)**
    - [ ] Finish Lab 10 by deadline_day:
        string_details(monday_week_one, 11, deadline_day=deadline_day)
- [ ] **string_details(monday_week_one, 12, 11, modules_list)**
    - [ ] Finish Lab 11 by deadline_day:
        string_details(monday_week_one, 12, deadline_day=deadline_day)
    - [ ] Finish portfolio piece 5 by deadline_day:
        string_details(monday_week_one, 12, deadline_day=deadline_day)
- [ ] **string_details(monday_week_one, 13, 12, modules_list)**
    - [ ] Finish portfolio piece 6 by deadline_day:
        string_details(monday_week_one, 13, deadline_day=deadline_day)
- [ ] **string_details(monday_week_one, 14, 13, modules_list)**
    - [ ] Finish portfolio pieces 7 and 8 by deadline_day:
        string_details(monday_week_one, 14, deadline_day=deadline_day)
- [ ] **string_details(monday_week_one, 15, 14, modules_list)**
    - [ ] Finish portfolio piece 9 and 10 by deadline_day:
        string_details(monday_week_one, 15, deadline_day=deadline_day)
- [ ] **Portfolio completion**
    - Due on deadline_day:
        string_details(monday_week_one, 15, deadline_day=deadline_day)

## Further guidelines

- According to reasons discussed and agreed upon in advance with the professor, there are some situations which might require some of these deadlines to be moved. If this is the case, I will reach out to the professor and agree on another deadline. The number of assignments that have to be completed satisfactory will not change because of these reasons.
- If the professor has any concerns about the assignments and whether they reach the standards of being completed "satisfactory", the professor will communicate these concerns with me and, if deemed appropriate by the professor, offer an opportunity to correct them.
- I pertain the right to, at any time, switch out any of the modules and labs with another module or lab in the course or change the order of them from what is currently specified in the contract. This will not affect the number of labs or modules that are to be completed according to the contract. It could however move a deadline for a lab to the appropriate deadline considering the module the lab belongs to. For example, if deciding to switch out lab 11 with lab 12, then lab 12 will be due the week I work on module 12, not module 11. Any such changes to modules or labs will be noted in this contract for reference, but will not require notifying the professor otherwise.
- Any other part of this contract can be changed before the final grade is set if agreed upon by both myself and the professor.


Comment: Now, I suggest that you knit the document. You can do this by pushing the "Knit" button with a blue yarn ball above this screen in Rmarkdown. To see the changes, push it to Github and look at the file there. If you feel more advanced, you can also change the output type to a html document in the YAML header. However, note that this will mess up some of the formatting, so I suggest to only do this temporarily while messing with the document and then switching back to the Github document type.

When looking at your knitted document, you will now see the standard schedule based on the dates and information you put in as parameters in the YAML header. There are a few things I suggest you look over and change as it fits you:

- There are currently mode modules than there are weeks in the semester. That means that you can't get through all the modules. If you want, you can switch out any of the modules in the contract with another module. The module is determined based on the number inputted as the third parameter in the string_details function. For example, in the following code "string_details(monday_week_one, 11, 12, modules_list)", the module number would be 12. If you are wondering what module module 12 is, you can go to the code block that defines the list "module_list" and count. Module 12 would be the topic that corresponds to the 12th topic in that list.

- In addition, there are also more labs that what is required to get an "A". You can therefore also change which labs you are doing. This is just written in the standard text (not code) in the contract, so to do that, simple remove the line with the lab you don't want and add it somewhere else, changing out the lab number. For example, if you do not want to do lab 10, delete the line stating "- [ ] Finish Lab 10 by deadline_day:
string_details(monday_week_one, 11, deadline_day=deadline_day)" and add this, switching out the lab number with another lab you want to do and any other parameteres that need to be adjusted, under the relevant module.

- You can move around when to do labs and any of the other things that have to be done. You can do this simply by copy pasting the text and code associated with it and move it around. For example, if you know that you have a busy week one week, you might want to move any portfolio project deadlines to the following week. Do for example look at when your thesis is due and see whether you want to keep the time around then more open.

- Look over when spring break is and move any assignments to other weeks (unless you want deadlines during spring break)

- As you finish assignments or modules, you can mark them with a check. The "[ ]" indicates an empty check box, while "[x]" indicates a checked box.

When you are done with the edits to the contract, you can knit it again, push it to Github, and look over it to see that everything looks good. -->




<!--- This contract is adapted from Annie Somerville's contract https://github.com/anniehsom -->




