---
title: "Regex"
---

Look at this book chapter that has a part on regex and which is what I used for vectorized operations: https://bookdown.org/rdpeng/rprogdatascience/regular-expressions.html

Also this: https://r4ds.hadley.nz/regexps

Used the cheatsheet at this resrouce: https://hypebright.nl/en/r-en/ultimate-cheatsheet-for-regex-in-r-2/

Goals of the current portfolio project:

- Understand the overall logic of regex
- Learning some basic regex expressions
- Getting confident enough with regex that I can decode and make regex expressions, even if it requires some Googling to look up symbols
- Demystifying regex


## Basics of Regex

Regex expressions consists of literals and metacharacers, which is like the actual words and grammar of a language.

The simplest regex expression is to just have one literal and no metacharacters. For example, you can have the expression "golf" which gives you all the lines that contains the string "golf".

Some of the metacharacters:

- "^" means start of the line
  - E.g. ^I think, will find all lines that start with "I think"
- "$" means end of the line
  - E.g. morning$ finds all lines that end with "morning"
- "[]" allows for several characters that would be accepted
  - E.g. "[Bb] [Uu] [Ss] [Hh]" find all lines that have the word "bush" written, no matter whether the characters are all small letters, capital letters, or a mix between them. For example, "bush", "Bush", and "BUSH" would all be matched with this expression
  - You can also include ranges of letters or numbers within the square brackets
    - E.g. [a-z],[0-9], or [a-zA-Z]
- "[^]" means do not match
  - E.g. [^?.]$ would be all lines that do not end with ? or .
- "." means any character
  - E.g. 9.11 could match with "9-11", "9/11", and "9211"
  - The period can also match nothing, like "911"
- "|" means or
  - E.g. flood|fire would match any line that contains flood or fire
- "()" indicates that whatever is before it goes for everything inside of the parenthesis
  - E.g. ^([Gg]ood|[Bb]ad) means that the line has to start with either "Good", "good", "Bad", or "bad". While ^[Gg]ood|[Bb]ad would mean that it has to start with "Good" or "good", or contain "Bad" or "bad"
- "?" means that the part is optional, but if you have, it can only happen once. It either has the character before it or nothing, but it can't have anything else, and it can't have anything else following it
  - [Gg]eorge( [Ww]\.)? [Bb]ush would accept "George W. Bush", but also just "George Bush"
- "\" means you escape the regex meaning of that character
  - [Gg]eorge( [Ww]\.)? [Bb]ush would mean you are looking for e.g. "George W. Bush" while just having [Gg]eorge( [Ww].)? [Bb]ush would mean there could be any character after the W, such as "George  WA Bush"
  - You can also do this by enclosing the character in square brackets, e.g. [.] would match a period only
- "*" means repeat any number of times, including 0
  - E.g. (.*) would match with lines containing (), either empty or with any string of any length
  - This metacharacter is greedy, meaning that it will match the longest possible match it can find
    - E.g. ^s(.*)s will match with the whole string in "sitting in starbucks" and not just the "sitting in s" part, since it wants as much as possible
    - You can turn off the greedy function with a "?", to make it lazy instead
      - ^s(.*?)s$
- "+" means repeated any number of times, but at least once
  In contrast to *, which is any number of times, including zero
  - E.g. (.+) would match () with any string of any length in it, but not empty
- "{}" are interval ranges of how many times something can be repeated
  - E.g. [Bb]ush( +[^ ]+ +){1,5} debate would match with any string that has "Bush" or "bush", then between one or five words, then the word "debate"
  - You do not have to specify a range, you can also put in only one number, meaning that it has to be repeated exactly that number of times, or a number with a comma, meaning it has to be repeated at least the specified number of times, but with no upper limit
    - E.g. {2} or {3,}
- "\1" or any other number means find the repeat of what was matched earlier in the parentheses. The number represents what group to find the same match as.
  - E.g. (\\d\\d)\\+(\\d\\d)=\2\\+\1 could match 12+65=65+12 
  - +([a-zA-Z]+) +\1 + would match any lines that have two words that are repeated after each other, such as "one one" or "so so"
  - You can use this with str_replace to switch the order of characters in a string
  - If you need more than 9 back-references (in which you should probably name them instead), some languages interpret \\10 as a back-reference to 1 with a 0 afterward and other to the group 10. You can write it as \\g{10} to make sure it is interpreted as the category 10
- You can name a capture group with (?<NAME>regex)
  - It is a little unclear how to get the backreference, it should be either \\k<NAME> or (?P=NAME). The code to capture the replacement string is also a little unclear, but could be ${NAME}, \\g<NAME>, $+{NAME}, or it is not possible and you have to use just \\1
- Capture groups are numbered from left to right, even if they do not capture anything. Likewise, if you run over a capture group several times, it will still just have that one number it got originally. If you capture several matches for one group, it will return the last match when called upon
  
  
Most of these notes come from [this lecture]([https://www.youtube.com/watch?v=NvHjYOilOf8)


## Regex functions in R

Most of these notes are taken from the bookchapter on [Regular Expressions in the R Programming for Data Science book](https://bookdown.org/rdpeng/rprogdatascience/regular-expressions.html). In addition, some are also taken from this [Datacamp Regex tutorial](https://www.datacamp.com/tutorial/regex-r-regular-expressions-guide)

Here are some of the main R functions used with regex:

- grep() - Searches for matches with a regex and returns a vector with the indices for those matches
  - Setting the parameter value = TRUE will return a vector with the actual string matches instead
  - Only gives you the index of the whole relevant string, not where the match is on that string. regexpr() can give you the information of exactly where the match occur in the matched string
- grepl() - Searches for matches with a regex and returns a vector with TRUE and FALSE values
- regexpr() - Searches for matches with a regex and returns both the (first) start index of that match and the length of the string that matches
  - Only gives you the first match of the string. If you want all matches, you have to use gregexpr()
- gregexpr() - Searches for matches with a regex and returns both the start index of that match and the length of the string that matches. Returns all instances of the match, even if one the same string (i.e. item in the vector)
  - The g here stands for global
- sub() - Searches for matches with a regex and replaces that (first) match with what you specify
  - Will only replace the first match in a string, if you want to replace all matches in the string, use gsub()
- gsub() - Searches for matches with a regex and replaces that match with what you specify
- regexec() - Searches for matches with a regex, where part of the regex is in a parenthesis, and returns both the start character index of the match and the length of it, as well as the start character index of the match with the part that is in the parenthesis and the length of that part
  - E.g. regexec("<dd>[F|f]ound on (.*?)</dd>") would give both the start character index of the "<" that matches the rest of the expression and the length of the match, in addition to the first character index of the character starting after "on " and how long that is.
- regmatches() - Like regexec(), but returns the actual matches of the string, as well as the part specified in the parenthesis
- substr() - If you have the indeces of strings already, you can use substr() to extract the relevant string by index


### Tidyverse - Stringr

Tidyverse has the library stringr which has a maybe more intuitive function setup and names. For example, all the functions take the data as the first argument and the regex as the second argument.

- str_view() - shows you the string, where the match in your string is highlighed by being surrounded with <>
- str_subset() - like grep(value = TRUE) which return a character vector with the matches only
- str_which() - returns an integer vector giving the position of the strings that match
- str_detect() - like grepl() which returns a TRUE/FALSE vector for matches
  - You can combine filter and str_detect to filter by a regex
    - E.g. filter(str_detect(name, "x"))
  - You can also combine summarize or other stat functions with filter to calculate stats by the regex
    - E.g. mean(str_detect(name, "x")) will give proportions of names with an x in it per year
- str_extract() - like regexpr() and regmatches(), which extracts the string matches of the output
- str_match() - like regexec(), returning a matrix with the parenthesized sub-expressions
  - First column is first character of match and second is first character of match with the content in the parenthesis
- str_replace() - like sub(), replacing the first string
- str_replace_all() - like gsub, replacing all the strings
- str_locate() - like regexpr(), which returns the index of the first match and the length of the match, for the first match
- str_locate_all() - like gregexpr(), which returns the index of the first match and the length of the match, for all the matches
- str_count() - counts the number of matches in each string
  - You can combine this with mutate to e.g. make a new variable counting the number of vowels in a string
- separete_wider_regex() - take information from one column and separete it into several columns based on a regex
  - E.g. separate_wider_regex(str, patterns = c("<", name = "[A-Za-z]+", ">-", gender = ".", "_", age = "[0-9]+")) will get the information out of strings like "<Sheryl>-F_34"
  - If it fails, you can apparently use too_few = "debug", I don't know what it does, but it should be helpful


#### Optional parameters

- ignore_case = TRUE - the regex will ignore whether the characters are lower or upper case
- dotall = TRUE - lets a . match everything, including a new line?
- multiline = TRUE - matches the start or end of each line instead of just each string
  - Instead of being lazy based on string, it is lazy based on each new line
- comments = TRUE - ignores spaces, newlines, and # and everything following it in your expression. You can therefore add spaces and comments in the middle of your expresison (with line shifts) to make it more readable
  - If you then want to match a space, escape it with a backslash
  


## Special characters from literals

You can use a backslash to make normal literals a metacharacter. All of these should follow a backslahs, but aren't here as that is considered formatting in R:

- w - any word character, including digit, letter, and underscore
- W - any non-word character
- d - any digit
- D - any non-digit
- s - any space character, including space, tab, and new line
- S - any non-space character
- b - a word boundary, such as a space or parenthesis before or after what is specified in the regex
  E.g. double backslash and bab matches "ab" in "abc", but not "bab", as that word doesn't start or end with "ab"
- B - a non-word boundary, such as another character after what is specified before this
  E.g. double backslash and Bab matches "ab" in "dabc", but not "abc", as that word starts start (or end) with "ab"
- n - a new line
- t - a tab
- v - a vertical tab
- < - beginning of a word
- > - end of a word
- A - beginning of a string
- z or Z - end of a string
  Depends on programming language
- G - beginning of string or end of previous match
  - E.g. if you want to only get the results from Jane on a score board, you can use the following regex (?:Jane|\G) \w+:(\d+) to get the numbers from "Tarzan A:33 B:32 C:36 Jane A:35 B:33 C:31"
    - You could also do this will lookbehinds, but G is more economical
  
  
## Inline Modifiers

Modifiers change the mode of the following regex part. You do not to include the following part in parenthesis

- (?i) - case-insensitive mode
- (?s) - matches across lines
  - Like if everything was on one line
- (?m) - multiline mode
  - Usually, anchors like ^ or $ only match the beginning or end of a string. If you turn on multiline mode, it will match the end or beginning of each line instead
- (?x) - free-spacing mode
  - You can write your regex with whitespace and line breaks that are not interpreted as characters to be matched. This allows for spacing out the regex to be more readable
  - E.g. var wordWithDigitAndCapRegex = new Regex(
@"(?x)      # Free-spacing mode

  ^         # Assert that position = beginning of string
  
  #########   Lookahead   ##########
  (?=       # Start lookahead
     \\D*       # Match any non-digits
     \\d        # Match one digit
  )         # End lookahead

  ######## Matching Section ########
  \\w*       # Match any word chars
  [A-Z]     # Match one upper-case letter
  \\w*       # Match any word chars
  
  $         # Assert that position = end of string
");
  - Now, to match a space, use either [ ] or "\\ "
  - Also, make sure you turn on free-space mode before using a space or line break in your code
  - Lastly, be aware that whitespace still separates components in the code. For example, \\12 is different from \\1 2
- (?n) - turns all parentheses into non-capture mode



## Built-in classes

Some of the above can also be specified as built-in classes with the following formatting [[:class:]]. Most of these have alternatives above.

- [[:alpha:]] - any letter
- [[:lower:]] - any lowercase letter
- [[:upper:]] - any uppercase letter
- [[:digit:]] - any digit
- [[:alnum:]] - any letter or number
- [[:xdigit:]] - any hexadecimal digit
- [[:punct:]] - any punctuation character
- [[:graph:]] - any letter, number, or punctuation character
- [[:space:]] - e.g. a space, a tab, or a new line
- [[:blank:]] - blank characters, such as space and tab


## Lookarounds
Lookarounds will look for the match you specify, either before or after the match (based on your expression). It will only match if the lookaround condition is met, but it will not actually capture the part in the lookaround. Lookahead or lookbehind refers to which direction it is looking in. The reason it doesn't capture anything is that it is like it hasn't moved further in reading the string when reaching a lookaround, is stays stagnant, looks ahead or behind (without moving) and then it starts moving when it gets to the code past the lookaround 

- (?=) - Positive lookahead
  - E.g. if you have (?=\\d{10})\\d{5}, it is similar as saying, if there are 10 digits here, match the first 5 of them
- (?<=) - Positive lookbehind
  - E.g. 	if you have (?<=\\d)cat, it is simlar as saying if there is a number before "cat", match with "cat"
- (?!) - Negative lookahead
  - E.g. if you have (?!theatre)the\w+, it is simlar to saying if the word isn't preeceded by "theatre", match "the" and any letter after it
- (?<!) - Negative lookbehind
  - E.g. if you have \w{3}(?<!mon)ster, it is the same as saying if you have three letters, that are not "mon", and the "ster", match those three letters and "ster"
  
- If you test multiple conditions, you can usually use n-1 lookarounds, where n is the number of conditions you have. This is because you need to capture something too, so the last condition can be a capture group instead of a lookaround.
- Also be aware, if you test multiple conditions, that since the lookahead doesn't move, if you have two lookaheads, they will start from the same position, not subsequent positions.
- When you decide on whether you should use a lookahead or lookbehind, see what would require matching the fewest characters. There is usually one position that is more efficient than the other.
- You can nest lookarounds, for example this regex \\d+(?=_(?!_)) to find numbers that is followed by one, but not more than one underscore.
- It is often good practice to anchor lookarounds, as that makes them fail or succeed immediately, instead of running through the whole string, as long as that is not what we want to do


## Other more advanced stuff

- (?:) - a non-capture group, so that you do not capture what is inside of the group
- [[:<:]] - beginning of word boundary. Only match if at the beginning of a word. Nothing can come before it, the word starts with what has been provided
  - E.g. [[:<:]]cat matches cat and catfish, but not tomcat
  - Similar to \b(?=\w)?
- [[:>:]] - end of word boundary, nothing can come after it, the word stops there
  - E.g. cat[[:>:]] matches cat and tomcat, but not catfish
  - Similar to \b(?<=\w)?

There is a difference between delimiters and boundaries. Boundaries look at whether there is a difference between what comes before and after the relevant part. A lookaround will only look in one direction. You can however use both a lookahead and lookbehind to detect boundaries.

If you make a boundary yourself, you can define it and then later call it by that name. For example:

(?x)             # free-spacing mode
(?(DEFINE)       # Define some subroutines
   (?<A1>           # Define "A1" boundary
                    # This boundary matches when
                    # one side is a letter and
                    # the other is a number
   (?i)(?<=^|\\d)(?=[a-z])|(?<=[a-z])(?=$|\\d)
   )                # End A1 definition
)                # End DEFINE

The actual regex matching starts here
We can use our "A1" boundary wherever we like
(?&A1)cat(?&A1)



## To do list

- Work through the last few crossword regex exercises and document it
- Go through the last black belt pages on rexegg page
- Go over all your notes and organize it better
- Check the formatting of the rendered document. The special characters tends to be read as a special character by rmarkdown


