---
title: "Thesis - Data Analyses"
---

The following project is a continuation of project 7, where I am doing the data analyses for my thesis on the data that was wrangled in the previous project. You can see that I am using more dplyr here, but that I turn to base R more towards the end, because I ran short on time to get the results for my thesis and I can still code faster in base R for the more complicated scenarios. I also borrowed some of the code for the tri-factor models from a previous project that I used base R for. However, I did learn a lot about Tidyverse from working on this project, which is reflected in project 4.

The data analyses document contains multiple versions of some analyses and plots as it is made to be one bigger document containing everything I have needed at any point, and not be one coherent narrative of the analyses. There might therefore be some redundancies from changing needs throughout working on the project. Everything should be well-commented and documented though.

Similarly to with the last project, the data is confidential and the portfolio webpage template didn't work well with an html file attached, so I will instead just link to the html page in the portfolio repository that you can download and view yourself.

Also note that there is a lot of output from creating the mplus compatible data with MplusAutomation. I have not yet found a combination of chunk options that shows the chunk code, but hides the output. Therefore, there is some junk output to scroll through in the html file.

<br>

**You can find the html file for the data analyses [here](https://github.com/lzapffe/ds_portfolio/blob/main/Data_Analysis.html)**