<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Vectorized Operations</title>

<script src="site_libs/header-attrs-2.29/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>









<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Portfolio</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="about.html">About</a>
</li>
<li>
  <a href="p01.html">Portfolio 1</a>
</li>
<li>
  <a href="p02.html">Portfolio 2</a>
</li>
<li>
  <a href="p03.html">Portfolio 3</a>
</li>
<li>
  <a href="p04.html">Portfolio 4</a>
</li>
<li>
  <a href="p05.html">Portfolio 5</a>
</li>
<li>
  <a href="p06.html">Portfolio 6</a>
</li>
<li>
  <a href="p07.html">Portfolio 7</a>
</li>
<li>
  <a href="p08.html">Portfolio 8</a>
</li>
<li>
  <a href="p09.html">Portfolio 9</a>
</li>
<li>
  <a href="p10.html">Portfolio 10</a>
</li>
<li>
  <a href="p11.html">Portfolio 11</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Vectorized Operations</h1>

</div>


<p>One thing that I have always struggled with, going from programming
in Python to R, is vectorized operations. I feel like loops make a lot
of sense, and when planning out the logic of some code, or writing it, I
can easily figure out how to do it with loops, but I struggle figure out
how to think about it with vectorized operations. I think part of that
is that it just takes a mentality shift and the other part is that I
don’t know how the functions for vectorized operations work well enough.
Therefore, with this project, I will take a deep-dive into vectorized
operations and get some practice with it, so that I hopefully feel
confident using vectorized operations later on when writing code.</p>
<p>Goals for the project:</p>
<ul>
<li>Learning about the logic of vectorized operations</li>
<li>Learning about the different functions for vectorized operations in
R, including apply(), lapply(), and mapply()</li>
<li>Comparing and contrasting writing vectorized vs looped code</li>
<li>Getting more experience with vectorized operations so that I can
confidently apply it to future coding projects</li>
</ul>
<div id="the-basics-of-vectorized-operations" class="section level1">
<h1>The Basics of Vectorized Operations</h1>
<div id="examples-of-simple-vectorized-operations"
class="section level2">
<h2>Examples of simple vectorized operations</h2>
<p>This <a
href="https://bookdown.org/rdpeng/rprogdatascience/vectorized-operations.html">book
chapter</a> had a good example of really basic vectorized operations.
Contrasting the following two ways of adding two vectors:</p>
<pre class="r"><code>x &lt;- 1:4
y &lt;- 6:9 
z &lt;- x + y
z</code></pre>
<pre><code>## [1]  7  9 11 13</code></pre>
<pre class="r"><code>x &lt;- 1:4
y &lt;- 6:9
for(i in seq_along(x)) {
      z[i] &lt;- x[i] + y[i]
}
z</code></pre>
<pre><code>## [1]  7  9 11 13</code></pre>
<p>When seeing it written out like that, I realize that I already use
some basics of vectorized operations.</p>
<p>Similarly, this is also vectorized operations:</p>
<pre class="r"><code>x &lt;- 1:4

x &gt; 2</code></pre>
<pre><code>## [1] FALSE FALSE  TRUE  TRUE</code></pre>
<p>This is with matrices:</p>
<pre class="r"><code>x &lt;- matrix(1:4, 2, 2)
y &lt;- matrix(rep(10, 4), 2, 2)
print(x)</code></pre>
<pre><code>##      [,1] [,2]
## [1,]    1    3
## [2,]    2    4</code></pre>
<pre class="r"><code>print(y)</code></pre>
<pre><code>##      [,1] [,2]
## [1,]   10   10
## [2,]   10   10</code></pre>
<pre class="r"><code>x * y </code></pre>
<pre><code>##      [,1] [,2]
## [1,]   10   30
## [2,]   20   40</code></pre>
</div>
<div id="the-different-functions-for-vectorized-operations-in-r"
class="section level2">
<h2>The different functions for vectorized operations in r</h2>
<p>This information is taken from on chapter 16 - <a
href="https://bookdown.org/rdpeng/rprogdatascience/loop-functions.html">Loop
Functions</a> in the open source textbook “R programming for data
science”</p>
<div id="lapply" class="section level3">
<h3>lapply()</h3>
<p>lapply() returns a list, hence the “l”.</p>
<p>It takes three arguments, a list to do an operation on, the function,
and any other parameters</p>
<p>If the input is not a list, it will be converted to a list
automatically using as.list()</p>
<p>When you pass a function through lapply() (second parameter), it will
input the list you have as the first parameter of that function. For
example, in mean(), the first argument is the object to calculate the
mean from and the rest of the parameters include e.g. whether parts of
the object should be trimmed (with trim).</p>
<p>If the function you pass through lapply() has more parameters that
you want to specify, such as trim = 0 in mean(), you can add those as
extra parameters to lapply() and they will be passed down into the
function you specify. For example, you could here have written lapply(x,
mean, trim = 0).</p>
<p>You can enter functions that you define yourself into lapply(). You
can even define it in the lapply() function itself. for example as
“lapply(x, function(elt) { elt[,1] })”. This creates an
<strong>anonymous function</strong> that only exists for the lapply()
command and then disappears.</p>
</div>
<div id="sapply" class="section level3">
<h3>sapply()</h3>
<p>sapply() is very similar to lapply(), but it simplifies the results.
For example, if you run lapply() on a vector with three items, it will
return a nested list where each list has one item each. However, if you
run sapply() it will make it one vector with several items. Similarly,
if all lists that you input has the same number of items, sapply() will
make it into a matrix, instead of nested lists. However, if none of
these two situations apply, it will just produce the same nested lists
as lapply() does.</p>
<p>See here for an example taken from the book chapter:</p>
<pre class="r"><code>x &lt;- list(a = 1:4, b = rnorm(10), c = rnorm(20, 1), d = rnorm(100, 5))
lapply(x, mean)</code></pre>
<pre><code>## $a
## [1] 2.5
## 
## $b
## [1] 0.1086965
## 
## $c
## [1] 1.036139
## 
## $d
## [1] 5.017537</code></pre>
<pre class="r"><code>x &lt;- list(a = 1:4, b = rnorm(10), c = rnorm(20, 1), d = rnorm(100, 5))
sapply(x, mean)</code></pre>
<pre><code>##         a         b         c         d 
## 2.5000000 0.0786398 1.1384882 5.1394174</code></pre>
</div>
<div id="tapply" class="section level3">
<h3>tapply()</h3>
<p>It sort of groups part of your vector together. So instead of maybe
having a nested list like x &lt;- c((1, 2, 3,),(4, 5, 6),(7, 8, 9)), you
can have the list x &lt;- c(1, 2, 3, 4, 5, 6, 7, 8, 9) and the list y
&lt;- c(1, 1, 1, 2, 2, 2, 3, 3, 3). You can then define to group the
calculations in x by the membership in y with tapply().</p>
<p>For example, tapply(x, y, mean)</p>
<p>There is also a parameter called simplify (TRUE or FALSE). If it is
true it gives output similar to that of sapply(), while if it is false,
it will give output similar to that of lapply().</p>
</div>
<div id="apply" class="section level3">
<h3>apply()</h3>
<p>Used on an array, like a matrix. You can specify which direction you
want it to act on, either rows or columns.</p>
<p>The second parameter, called MARGINS, determine whether you apply the
funtion to the column or the row. If the value is 1, you collapse the
columns and retain the rows. If the value is 2, you collapse the rows
and retain the columns. See the following examples, taken from the
bookchapter, for reference:</p>
<pre class="r"><code>x &lt;- matrix(rnorm(200), 20, 10)
apply(x, 2, mean)  ## Take the mean of each column</code></pre>
<pre><code>##  [1]  0.10081086  0.12144049  0.07251878  0.36870103  0.19511047  0.04175525
##  [7] -0.31455933  0.17853417  0.08659156 -0.02026260</code></pre>
<pre class="r"><code>x &lt;- matrix(rnorm(200), 20, 10)
apply(x, 1, sum)   ## Take the mean of each row</code></pre>
<pre><code>##  [1] -10.725517272  -1.467577905   5.084395689   1.855834905  -0.940484890
##  [6]   7.822763512  -2.580626517   0.007367825   3.570759101  -5.648056152
## [11]   1.777370480  -7.411632154   2.525696940   0.033679983  -4.084617997
## [16]  -3.041521123   4.088681038   0.269183588   6.332246245   0.063632391</code></pre>
<p>The following are some examples of functions that could be written as
apply()</p>
<p>rowSums = apply(x, 1, sum) rowMeans = apply(x, 1, mean) colSums =
apply(x, 2, sum) colMeans = apply(x, 2, mean</p>
</div>
<div id="mapply" class="section level3">
<h3>mapply()</h3>
<p>mapply() can iterate over multiple r objects at the time, like
running lapply() in paralell.</p>
<p>For mapply(), the first parameter is the function, not the object to
run it for.</p>
<p>Here is an example of how mapply() saves space. For example, instead
of writing</p>
<pre class="r"><code>list(rep(1, 4), rep(2, 3), rep(3, 2), rep(4, 1))</code></pre>
<pre><code>## [[1]]
## [1] 1 1 1 1
## 
## [[2]]
## [1] 2 2 2
## 
## [[3]]
## [1] 3 3
## 
## [[4]]
## [1] 4</code></pre>
<p>You can use mapply() and write</p>
<pre class="r"><code>mapply(rep, 1:4, 4:1)</code></pre>
<pre><code>## [[1]]
## [1] 1 1 1 1
## 
## [[2]]
## [1] 2 2 2
## 
## [[3]]
## [1] 3 3
## 
## [[4]]
## [1] 4</code></pre>
<p>Here, 1:4 is passed to rep as the first parameter and 4:1 as the
second.</p>
<p>You can also use mapply() to run vectorized operations with functions
that do not support vectorized operations. For example, here is how the
book chapter demonstrated it:</p>
<pre class="r"><code>sumsq &lt;- function(mu, sigma, x) {
         sum(((x - mu) / sigma)^2)
}

# Generate data in a list
x &lt;- rnorm(100)</code></pre>
<p>Here we are defining a function to calculate sums of squares and we
want to do it for values of mu and sigma increasing from 1 to 10. If we
try doing this in the function itself, which is not adapted for
vectorized operations, we only get one number.</p>
<pre class="r"><code>sumsq(1:10, 1:10, x)  ## This is not what we want</code></pre>
<pre><code>## [1] 100.9701</code></pre>
<p>While we can apply mapply() to run the 10 values in paralell.</p>
<pre class="r"><code>mapply(sumsq, 1:10, 1:10, MoreArgs = list(x = x))</code></pre>
<pre><code>##  [1] 149.61056 104.01449  98.05615  96.80955  96.61601  96.71799  96.90398
##  [8]  97.10535  97.29864  97.47637</code></pre>
<p>You can also apparently do this with the Vectorize() function</p>
<pre class="r"><code>vsumsq &lt;- Vectorize(sumsq, c(&quot;mu&quot;, &quot;sigma&quot;))
vsumsq(1:10, 1:10, x)</code></pre>
<pre><code>##  [1] 149.61056 104.01449  98.05615  96.80955  96.61601  96.71799  96.90398
##  [8]  97.10535  97.29864  97.47637</code></pre>
<p>I don’t think I fully understand how this works yet, but I might get
it a little more later. Or it might not be the most important thing to
know.</p>
</div>
<div id="split" class="section level3">
<h3>split()</h3>
<p>The book chapter also mentions split(), as this seems to often be
used with vectorized operations. You can use it to divide out a part of
the items and run a function only on these. It takes the parameters x
(vector or data frame), function, and drop = TRUE/FALSE. Seems like it
works with factors.</p>
<pre class="r"><code>x &lt;- c(rnorm(10), runif(10), rnorm(10, 1))
f &lt;- gl(3, 10)
print(f)</code></pre>
<pre><code>##  [1] 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3
## Levels: 1 2 3</code></pre>
<pre class="r"><code>split(x, f)</code></pre>
<pre><code>## $`1`
##  [1] -1.43539675  0.74258982 -0.23285498  0.45596294  0.82536741  0.41122698
##  [7]  1.60180268  0.09021498 -2.93822119  0.22074564
## 
## $`2`
##  [1] 0.45072635 0.96196731 0.85126878 0.41867323 0.09053235 0.19080976
##  [7] 0.48191501 0.43680248 0.75471749 0.17389318
## 
## $`3`
##  [1] 0.9110370 1.4243065 1.2042215 0.8150286 0.5292578 1.2827065 0.5664749
##  [8] 3.5031179 1.1326513 2.0512901</code></pre>
<p>This seems very similar to tapply(), but with factors instead of just
a list.</p>
<p>This is an example in combination with lapply()</p>
<pre class="r"><code>lapply(split(x, f), mean)</code></pre>
<pre><code>## $`1`
## [1] -0.02585625
## 
## $`2`
## [1] 0.4811306
## 
## $`3`
## [1] 1.342009</code></pre>
<p>With this, you can for example look at a data frame and split up the
calculations or stats based on a variable (as a factor), such as month
or city. You can even split it up in combinations of two or more
variables, e.g. with (split(x, list(f1, f2))).</p>
<p>Remember from earlier, that tapply() is like split() and lapply(),
but for vectors only. That means that you cannot use it on data
frames.</p>
</div>
</div>
<div id="check-in" class="section level2">
<h2>Check-in</h2>
<p>Ok, I think I am starting to get a basic overview of the different
functions, what they do, and how they work. Now, I think I might need
some practice actually using them. I have asked ChatGPT to come up with
exercises for me, so I will use that to get more comfortable using these
vectorized operations.</p>
</div>
</div>
<div id="practice" class="section level1">
<h1>Practice!</h1>
<p>So far, I have learned about apply(), lapply(), sapply(), tapply(),
mapply(), and split() with lapply(). I know need some practice using
these functions to get comfortable with the logic behind them, when to
use each, and how they work.</p>
<p>First, I fed ChatGPT with all the notes I have up until this point
and asked it to make some exercises, with varying difficulty, that could
be used to practice what is in this document so far and further deepen
my understanding. Here are some exercises and my solutions to them from
ChatGPT. Some of them might be slightly modified:</p>
<div id="simple-vectorized-operations" class="section level3">
<h3>1. Simple Vectorized Operations</h3>
<p>1.1. Create two vectors, a &lt;- 1:5 and b &lt;- 6:10. Then use
vectorized operations for the next steps.</p>
<pre class="r"><code>a &lt;- c(1:5)
b &lt;- c(6:10)
print(a)</code></pre>
<pre><code>## [1] 1 2 3 4 5</code></pre>
<pre class="r"><code>print(b)</code></pre>
<pre><code>## [1]  6  7  8  9 10</code></pre>
<p>Little reminder to myself: lists differ from vectors as a vector can
only have one type of items, e.g. numbers, characters, or logical
values, while lists can have a mix. You define a vector with c() and a
list with list(). I am pretty sure a c() with multiple data types will
just automatically be converted to a list, since R tends to to that type
of stuff.</p>
<p>1.2. Add, subtract, multiply, and divide the vectors.</p>
<pre class="r"><code>c &lt;- a + b
print(c)</code></pre>
<pre><code>## [1]  7  9 11 13 15</code></pre>
<pre class="r"><code>d &lt;- a - b
print(d)</code></pre>
<pre><code>## [1] -5 -5 -5 -5 -5</code></pre>
<pre class="r"><code>e &lt;- a * b
print(e)</code></pre>
<pre><code>## [1]  6 14 24 36 50</code></pre>
<pre class="r"><code>f &lt;- a / b
print(f)</code></pre>
<pre><code>## [1] 0.1666667 0.2857143 0.3750000 0.4444444 0.5000000</code></pre>
<p>As we learned about earlier, these kind of operations of the vectors
is already vectorized, you don’t have to use any of the functions like
apply()</p>
<p>1.3. Find which elements of a are greater than 3.</p>
<pre class="r"><code>g &lt;- a &gt; 3
print(g)</code></pre>
<pre><code>## [1] FALSE FALSE FALSE  TRUE  TRUE</code></pre>
<p>1.4. Rewrite the operations using loops instead of vectorized
operations. I’ll just do the last one from 1.3.</p>
<pre class="r"><code>g &lt;- c()
for (i in a) {
  if (i &gt; 3) {
    g &lt;- append(g, TRUE)
  } else {
    g &lt;- append(g, FALSE)
  }
}
print(g)</code></pre>
<pre><code>## [1] FALSE FALSE FALSE  TRUE  TRUE</code></pre>
<p>That was indeed a lot more work than using vectorized operations.</p>
</div>
<div id="matrix-operations" class="section level3">
<h3>2. Matrix Operations</h3>
<p>2.1. Create a matrix mat &lt;- matrix(1:9, nrow = 3).</p>
<pre class="r"><code>mat &lt;- matrix(1:9, nrow = 3)
print(mat)</code></pre>
<pre><code>##      [,1] [,2] [,3]
## [1,]    1    4    7
## [2,]    2    5    8
## [3,]    3    6    9</code></pre>
<p>2.2. Multiply each element of the matrix by 2 using vectorized
operations.</p>
<pre class="r"><code>mat_mult &lt;- mat*2
mat_mult</code></pre>
<pre><code>##      [,1] [,2] [,3]
## [1,]    2    8   14
## [2,]    4   10   16
## [3,]    6   12   18</code></pre>
<p>2.3. Find the square of each element in the matrix.</p>
<pre class="r"><code>mat_square &lt;- mat^2
mat_square</code></pre>
<pre><code>##      [,1] [,2] [,3]
## [1,]    1   16   49
## [2,]    4   25   64
## [3,]    9   36   81</code></pre>
<p>2.4. Check which elements are greater than 5.</p>
<pre class="r"><code>mat &gt; 5</code></pre>
<pre><code>##       [,1]  [,2] [,3]
## [1,] FALSE FALSE TRUE
## [2,] FALSE FALSE TRUE
## [3,] FALSE  TRUE TRUE</code></pre>
</div>
<div id="apply-1" class="section level3">
<h3>3. apply()</h3>
<p>Using apply()</p>
<p>3.1. Create a matrix mat &lt;- matrix(rnorm(20), nrow = 5).</p>
<pre class="r"><code>mat &lt;- matrix(rnorm(20), nrow = 5)
mat</code></pre>
<pre><code>##            [,1]       [,2]       [,3]        [,4]
## [1,]  0.2458405  2.4834622 -0.6381050 -0.52433477
## [2,]  1.2363148  0.4493713  0.3373775 -0.37457341
## [3,] -0.9850378  1.2318173 -0.3784656  0.44137698
## [4,] -0.8975814  1.1544584 -0.1821006 -0.02106525
## [5,]  0.4242128 -2.6301320  1.2497726  0.84842562</code></pre>
<p>3.2. Use apply() to calculate the mean of each row.</p>
<pre class="r"><code>apply(mat, MARGIN = 1,  mean)</code></pre>
<pre><code>## [1]  0.39171573  0.41212253  0.07742271  0.01342777 -0.02693024</code></pre>
<p>3.3. Use apply() to find the sum of each column.</p>
<pre class="r"><code>apply(mat, MARGIN = 2, sum)</code></pre>
<pre><code>## [1] 0.02374897 2.68897711 0.38847875 0.36982918</code></pre>
<p>3.4. Write a custom function that calculates the range (max - min)
and use apply() to calculate the range for each row.</p>
<pre class="r"><code>apply(mat, MARGIN = 1, function(x) {max(x)-min(x)})</code></pre>
<pre><code>## [1] 3.121567 1.610888 2.216855 2.052040 3.879905</code></pre>
<p>I might actually be a genius. Just saying.</p>
</div>
<div id="using-lapply-and-sapply" class="section level3">
<h3>4. Using lapply() and sapply()</h3>
<p>4.1. Create a list of numeric vectors:</p>
<pre class="r"><code>my_list &lt;- list(a = 1:5, b = rnorm(10), c = runif(20))
my_list</code></pre>
<pre><code>## $a
## [1] 1 2 3 4 5
## 
## $b
##  [1]  1.32745188  0.96562037 -0.31281573 -0.97599942  0.13460979  0.94047503
##  [7] -0.02794075  0.77015198  0.98889854  0.03009180
## 
## $c
##  [1] 0.617170976 0.369451697 0.785230602 0.266876426 0.639855548 0.075114211
##  [7] 0.625187044 0.253682892 0.462585453 0.008662377 0.890968527 0.479300378
## [13] 0.462295977 0.613420798 0.586291413 0.504742512 0.788883469 0.946769446
## [19] 0.412827094 0.620836265</code></pre>
<p>4.2. Use lapply() to calculate the mean of each vector.</p>
<pre class="r"><code>lapply(my_list, mean)</code></pre>
<pre><code>## $a
## [1] 3
## 
## $b
## [1] 0.3840543
## 
## $c
## [1] 0.5205077</code></pre>
<p>4.3. Use sapply() to calculate the standard deviation of each
vector.</p>
<pre class="r"><code>sapply(my_list, sd)</code></pre>
<pre><code>##         a         b         c 
## 1.5811388 0.7261279 0.2468330</code></pre>
<p>4.4. Create an anonymous function inside lapply() to find the sum of
squares for each vector.</p>
<pre class="r"><code>lapply(my_list, function(x) {sum(x^2)})</code></pre>
<pre><code>## $a
## [1] 55
## 
## $b
## [1] 6.220333
## 
## $c
## [1] 6.576169</code></pre>
</div>
<div id="using-tapply" class="section level3">
<h3>5. Using tapply()</h3>
<p>5.1. Create two vectors:</p>
<pre class="r"><code>values &lt;- c(10, 20, 30, 40, 50, 60, 70, 80)
groups &lt;- c(&quot;A&quot;, &quot;A&quot;, &quot;B&quot;, &quot;B&quot;, &quot;C&quot;, &quot;C&quot;, &quot;A&quot;, &quot;B&quot;)</code></pre>
<p>5.2. Use tapply() to calculate the mean of values grouped by
groups.</p>
<pre class="r"><code>tapply(values, groups, mean)</code></pre>
<pre><code>##        A        B        C 
## 33.33333 50.00000 55.00000</code></pre>
<p>5.3. Use tapply() to count the number of elements in each group.</p>
<pre class="r"><code>tapply(values, groups, length)</code></pre>
<pre><code>## A B C 
## 3 3 2</code></pre>
</div>
<div id="using-mapply---advanced" class="section level3">
<h3>6. Using mapply() - Advanced</h3>
<p>6.1. Write a function power_fun &lt;- function(base, exp) { base ^
exp }.</p>
<pre class="r"><code>power_fun &lt;- function(base, exp) { base ^ exp }</code></pre>
<p>6.2. Use mapply() to apply this function to base = c(2, 3, 4) and exp
= c(3, 2, 1).</p>
<pre class="r"><code>base = c(2, 3, 4)
exp = c(3, 2, 1)
mapply(power_fun, base, exp)</code></pre>
<pre><code>## [1] 8 9 4</code></pre>
<p>6.3. Compare the output with the manual calculation of each base
raised to its corresponding exponent.</p>
<pre class="r"><code>for (i in 1:length(base)){
  print(power_fun(base[i],exp[i]))
}</code></pre>
<pre><code>## [1] 8
## [1] 9
## [1] 4</code></pre>
</div>
<div id="combining-split-and-lapply---advanced" class="section level3">
<h3>7. Combining split() and lapply() - Advanced</h3>
<p>7.1. Create a data frame:</p>
<pre class="r"><code>df &lt;- data.frame(
  id = 1:12,
  group = rep(c(&quot;X&quot;, &quot;Y&quot;, &quot;Z&quot;), each = 4),
  score = rnorm(12, mean = 75, sd = 10)
)
df</code></pre>
<pre><code>##    id group    score
## 1   1     X 65.78225
## 2   2     X 78.35155
## 3   3     X 98.53186
## 4   4     X 76.81449
## 5   5     Y 76.67101
## 6   6     Y 80.01207
## 7   7     Y 88.83529
## 8   8     Y 73.17638
## 9   9     Z 79.58177
## 10 10     Z 73.36282
## 11 11     Z 93.98514
## 12 12     Z 88.89562</code></pre>
<p>7.2. Use split() to split the data frame by group.</p>
<pre class="r"><code>split(df, df$group)</code></pre>
<pre><code>## $X
##   id group    score
## 1  1     X 65.78225
## 2  2     X 78.35155
## 3  3     X 98.53186
## 4  4     X 76.81449
## 
## $Y
##   id group    score
## 5  5     Y 76.67101
## 6  6     Y 80.01207
## 7  7     Y 88.83529
## 8  8     Y 73.17638
## 
## $Z
##    id group    score
## 9   9     Z 79.58177
## 10 10     Z 73.36282
## 11 11     Z 93.98514
## 12 12     Z 88.89562</code></pre>
<p>7.3. Use lapply() to calculate the mean score for each group.</p>
<pre class="r"><code>lapply(split(df$score, df$group), mean)</code></pre>
<pre><code>## $X
## [1] 79.87004
## 
## $Y
## [1] 79.67369
## 
## $Z
## [1] 83.95634</code></pre>
<p>7.4. Write a combined split() and lapply() operation to count the
number of rows in each group.</p>
<pre class="r"><code>lapply(split(df, df$group), nrow)</code></pre>
<pre><code>## $X
## [1] 4
## 
## $Y
## [1] 4
## 
## $Z
## [1] 4</code></pre>
</div>
<div id="simulating-data-with-mapply---advanced" class="section level3">
<h3>8. Simulating Data with mapply() - Advanced</h3>
<p>8.1. Simulate data for 5 different groups, each with a mean and
standard deviation:</p>
<pre class="r"><code>means &lt;- c(5, 10, 15, 20, 25)
sds &lt;- c(1, 2, 3, 4, 5)
n &lt;- c(10, 15, 20, 25, 30)</code></pre>
<p>8.2. Use mapply() to generate random normal data for each group using
rnorm().</p>
<pre class="r"><code>mapply(rnorm, n, means, sds)</code></pre>
<pre><code>## [[1]]
##  [1] 4.547859 3.327237 5.109765 4.719630 5.396496 4.939478 6.223722 5.562379
##  [9] 5.011213 6.017168
## 
## [[2]]
##  [1]  6.993910  9.939807  7.770788 12.704072 11.446799  8.779442  9.316836
##  [8] 11.392556  7.799449 10.862195  9.123179  7.183747  6.933311 10.281304
## [15] 10.150755
## 
## [[3]]
##  [1] 12.57041 16.21233 15.91188 16.32299 12.72813 17.37519 13.06956 17.83711
##  [9] 13.42698 15.01833 20.65435 10.71640 14.36897 19.18413 16.82043 11.41515
## [17] 12.81246 15.11241 15.05740 14.65149
## 
## [[4]]
##  [1] 24.80955 23.16125 23.23779 22.32872 26.81563 19.35004 14.08357 22.77326
##  [9] 24.34130 20.13823 18.63163 17.30827 22.29097 21.14494 17.64018 14.04093
## [17] 22.94782 21.33090 20.51804 11.29346 19.97177 21.62907 23.70673 15.44418
## [25] 21.09894
## 
## [[5]]
##  [1] 20.271285 18.316222 29.209659 26.497203 25.706895 27.469241 20.397557
##  [8] 30.664449 20.738557 22.368359 21.903197 28.241586 22.361334 36.754206
## [15] 27.105726 30.090210 29.150717  7.901357 22.802805 28.838188 27.026893
## [22] 18.676905 15.323062 24.753634 31.807973 34.475026 28.644243 14.787176
## [29] 31.754267 24.922942</code></pre>
</div>
<div id="combining-multiple-functions---challenge"
class="section level3">
<h3>9. Combining Multiple Functions - Challenge</h3>
<p>9.1. Create a data frame:</p>
<pre class="r"><code>df &lt;- data.frame(
  category = rep(c(&quot;A&quot;, &quot;B&quot;, &quot;C&quot;), each = 5),
  value1 = rnorm(15, 50, 10),
  value2 = rnorm(15, 30, 5)
)
df</code></pre>
<pre><code>##    category   value1   value2
## 1         A 55.87498 25.40623
## 2         A 64.39462 34.17921
## 3         A 44.16020 37.06162
## 4         A 54.25231 20.55481
## 5         A 48.36061 29.25065
## 6         B 47.76512 30.02203
## 7         B 45.70527 33.34385
## 8         B 28.11363 21.03078
## 9         B 56.41590 25.51830
## 10        B 57.94035 29.58725
## 11        C 38.05629 36.48660
## 12        C 46.05396 31.71657
## 13        C 52.26031 22.42284
## 14        C 44.59432 29.18558
## 15        C 51.43379 34.91170</code></pre>
<p>9.2. Use split() and lapply() to calculate the mean of value1 and
value2 for each category.</p>
<pre class="r"><code>lapply(split(df$value1, df$category), mean)</code></pre>
<pre><code>## $A
## [1] 53.40855
## 
## $B
## [1] 47.18805
## 
## $C
## [1] 46.47974</code></pre>
<pre class="r"><code>lapply(split(df$value2, df$category), mean)</code></pre>
<pre><code>## $A
## [1] 29.2905
## 
## $B
## [1] 27.90044
## 
## $C
## [1] 30.94466</code></pre>
<p>9.3. Use mapply() to calculate the sum of squares for value1 and
value2 for each category.</p>
<pre class="r"><code>mapply(function(x) { sum(x)^2 }, split(df$value1, df$category))</code></pre>
<pre><code>##        A        B        C 
## 71311.82 55667.80 54009.14</code></pre>
<pre class="r"><code>mapply(function(x) { sum(x)^2 }, split(df$value2, df$category))</code></pre>
<pre><code>##        A        B        C 
## 21448.34 19460.87 23939.29</code></pre>
<p>9.4. Compare the results with a loop-based approach.</p>
<pre class="r"><code>vect_a &lt;- c()
vect_b &lt;- c()
vect_c &lt;- c()
for (i in 1:length(df$category)){
  if (df$category[i] == &quot;A&quot;) {
    vect_a &lt;- append(vect_a, df$value1[i])
  } else if (df$category[i] == &quot;B&quot;) {
    vect_b &lt;- append(vect_b, df$value1[i])
  } else {
    vect_c &lt;- append(vect_c, df$value1[i])
  }
}
(mean(vect_a))</code></pre>
<pre><code>## [1] 53.40855</code></pre>
<pre class="r"><code>(mean(vect_b))</code></pre>
<pre><code>## [1] 47.18805</code></pre>
<pre class="r"><code>(mean(vect_c))</code></pre>
<pre><code>## [1] 46.47974</code></pre>
<p>That was a lot more extensive and thought-consuming than using
vectorized operations, I see the appeal</p>
</div>
<div id="advanced-matrix-manipulations---challenge"
class="section level3">
<h3>10. Advanced Matrix Manipulations - Challenge</h3>
<p>10.1 Create a 3D array:</p>
<pre class="r"><code>arr &lt;- array(1:24, dim = c(4, 3, 2))
arr</code></pre>
<pre><code>## , , 1
## 
##      [,1] [,2] [,3]
## [1,]    1    5    9
## [2,]    2    6   10
## [3,]    3    7   11
## [4,]    4    8   12
## 
## , , 2
## 
##      [,1] [,2] [,3]
## [1,]   13   17   21
## [2,]   14   18   22
## [3,]   15   19   23
## [4,]   16   20   24</code></pre>
<p>10.2. Use apply() to calculate the sum along each dimension.</p>
<pre class="r"><code>apply(arr, MARGIN = 1, sum)</code></pre>
<pre><code>## [1] 66 72 78 84</code></pre>
<pre class="r"><code>apply(arr, MARGIN = 2, sum)</code></pre>
<pre><code>## [1]  68 100 132</code></pre>
<pre class="r"><code>apply(arr, MARGIN = 3, sum)</code></pre>
<pre><code>## [1]  78 222</code></pre>
<p>10.3. Use mapply() to scale the values in the array by different
factors for each layer.</p>
<pre class="r"><code>vect_mar &lt;- c(1, 2, 3)
vect_scale &lt;- c(10, 2, 3)
#mapply(function(x, y) {apply(arr, MARGIN = y, x*y)}, vect_mar, vect_scale)</code></pre>
<p>I got stuck here. I don’t know how to use anonymous functions to do
this. This is the solution that ChatGPT gave (with different variable
names):</p>
<pre class="rex"><code>arr &lt;- array(1:24, dim = c(4, 3, 2))  # A 4x3x2 array
factors &lt;- c(2, 3)  # Scaling factors for each layer

scaled_arr &lt;- mapply(function(slice, factor) slice * factor,
                     split(arr, slice.index(arr, 3)),  # Split by layers
                     factors,
                     SIMPLIFY = FALSE)  # Avoid simplifying to vectors
scaled_arr &lt;- array(unlist(scaled_arr), dim = dim(arr))  # Reshape to original dimensions</code></pre>
<p>Turns out that I misunderstood what ChatGPT meant with layers. I
though of that as being each dimension, but it meant each value of the
third dimension. Here is the code ChatGPT gave me when I asked it to
edit my code so that it would work:</p>
<pre class="r"><code>vect_mar &lt;- c(1, 2)
vect_scale &lt;- c(10, 2)

scaled_arr &lt;- mapply(
  function(margin, scale) {
    # Giving the data set as all rows, all columns, but varying levels
    apply(arr[, , margin], MARGIN = c(1, 2), function(x) x * scale)
  },
  vect_mar,
  vect_scale,
  # This part makes it so that the matrices are kept separate in the output and not combined + somehow making the third column part of first and second
  SIMPLIFY = FALSE
)

scaled_arr</code></pre>
<pre><code>## [[1]]
##      [,1] [,2] [,3]
## [1,]   10   50   90
## [2,]   20   60  100
## [3,]   30   70  110
## [4,]   40   80  120
## 
## [[2]]
##      [,1] [,2] [,3]
## [1,]   26   34   42
## [2,]   28   36   44
## [3,]   30   38   46
## [4,]   32   40   48</code></pre>
<p>I sort of get it, but not 100%. I think my main challenge here though
is the limitation in what I know about functions and maybe not so much
the vectorized operations. Functions might be an interesting portfolio
project for later. In the meantime, I will continue practicing
vectorized operations.</p>
</div>
<div id="working-from-loops-to-vectorized-operations---exercises"
class="section level2">
<h2>Working from loops to vectorized operations - Exercises</h2>
<p>The following section will have some exercisees converting code using
loops to vectorized operations. I wanted to do this because I feel like
I can fairly easily think in terms of loops when designing code and I
want to practice thinking with vectorized operations instead. In
addition, it will help compare and contrast loops with vectorized
operations. The exercises are taken from ChatGPT.</p>
<div id="multiply-rows-of-a-matrix-by-a-vector" class="section level3">
<h3>11. Multiply Rows of a Matrix by a Vector</h3>
<p>Code with Loops:</p>
<pre class="r"><code># A 4x3 matrix
mat &lt;- matrix(1:12, nrow = 4, ncol = 3)

# A vector of scaling factors
scaling &lt;- c(2, 4, 6, 8)

# Using a loop to multiply each row by its corresponding factor
result &lt;- matrix(0, nrow = 4, ncol = 3)
for (i in 1:nrow(mat)) {
  result[i, ] &lt;- mat[i, ] * scaling[i]
}
result</code></pre>
<pre><code>##      [,1] [,2] [,3]
## [1,]    2   10   18
## [2,]    8   24   40
## [3,]   18   42   66
## [4,]   32   64   96</code></pre>
<pre class="r"><code>mat &lt;- matrix(1:12, nrow = 4, ncol = 3)
scaling &lt;- c(2, 4, 6, 8)
#mapply(function(dat, scale) {})</code></pre>
<p>I think, at this point, that I can’t fully take advantage of the
vectorized operations before I learn to deal with functions better. I
will come back to this after I have worked through the module on
functions. If I still feel like I need more practice after that module,
I might make a separate portfolio project for that.</p>
</div>
</div>
<div id="to-do-list-for-finishing-the-project" class="section level2">
<h2>To do list for finishing the project</h2>
<ul>
<li>Add information about vapply()</li>
<li>Add a quick guide/summary of the functions to the end of the
document</li>
<li>Figure out how to use nested anonymous functions</li>
<li>Add the scenario from data wrangling the PAC data where the for loop
worked better than vectorized operations because it is recursive</li>
</ul>
</div>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
